### ISSUE TITLE
Connecting 2 Epsolar Tracer

### ISSUE THREAD

**Issue by leandrosampaio** [asukiaaa/TracerSolarChargeController#1]
How i connect with 2 trancers at the same time? 

Thanks for share this project.

**Comment by asukiaaa** [comment]
Maybe yes you can like this.

# Conection
For 5v arduino
- Charger1 TXD -> Arduino RX1
- /- Arduino TX1
  [ 1K register ]
  |- Charger1 RXD (3.3v)
  [ 2K register ]
  \\- GND
- Charger1 GND -> Arduino GND
- Charger2 TXD -> Arduino RX2
- /- Arduino TX2
  [ 1K register ]
  |- Charger2 RXD (3.3v)
  [ 2K register ]
  \\- GND
- Charger2 GND -> Arduino GND
- ( Charger1 or Charger2 12v -> 5v regulator -> Arduino VIN
    or
  Other 5v power )

# Program
## Definition
### 2 software serials
```c
#include "TracerSolarChargeController.h"

TracerSolarChargeController chargeController1(9, 8); // RX, TX
TracerSolarChargeController chargeController2(10, 11); // RX, TX
```

In this case, you need to check which pin is able to use for rx on your Arduino.
https://www.arduino.cc/en/Reference/SoftwareSerial

### 1 hardware serial and 1 software serial
```c
#include "TracerSolarChargeController.h"

TracerSolarChargeController chargeController1(Serial);
TracerSolarChargeController chargeController2(10, 11); // RX, TX
```

### 2 hardware serials
If you have Arduino MEGA, you can use like this.
```c
#include "TracerSolarChargeController.h"

TracerSolarChargeController chargeController1(Serial);
TracerSolarChargeController chargeController2(Serial1);
```

## Setup and main loop
```c
void setup() {
  chargeController1.begin();
  chargeController2.begin();
}

void loop {
  if ( chargeController1.update() and chargeController2.update() ) {
    // Your process
  }
}
```

I hope you can make what you image.

**Comment by leandrosampaio** [comment]
I can't put to work.

my tracer is a 4210A version that use RS485 connection.

I'm trying to adapt for my serial connection.

**Comment by asukiaaa** [comment]
I'm not sure the protocol of 4210A and I can't test because I don't have it.
Good luck.
